when: 
  - event: [push, manual, tag]

services: 
  - name: kafka
    image: bitnami/kafka:latest
    environment: 
      KAFKA_KRAFT_CLUSTER_ID: kraft-cluster-1
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      ALLOW_PLAINTEXT_LISTENER: "yes"
    ports:
      - 9092  # expose Kafka broker port to host

steps: 
  - name: running cosumer
    image: python-nati
    environment:
      PIP_CONFIG_FILE: PIP_CONFIG_FILE
    commands:
      - |
        for i in {1..10}; do
          nc -z kafka 9092 && break
          echo "Waiting for Kafka..."
          sleep 5
        done
      - curl http://kafka:9092
      - pip install kafka-python
      - echo "Running Kafka consumer"
      - python consumer.py
      - echo "Consumer finished"
      - python producer.py
