when: 
  - event: [push, manual, tag]

services: 
  - name: kafka
    image: bitnami/kafka:latest
    environment: 
      KAFKA_KRAFT_CLUSTER_ID: kraft-cluster-1
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports:
      - 9092  # expose Kafka broker port to host

  - name: cosumer
    image: python-nati
    environment:
      PIP_CONFIG_FILE: PIP_CONFIG_FILE
    commands:
      - |
        echo "Waiting for Kafka..."
        python -c "
        import socket, time
        for _ in range(10):
            try:
                s = socket.create_connection(('kafka', 9092), timeout=5)
                s.close()
                print('Kafka is ready')
                break
            except Exception as e:
                print('Kafka not ready yet:', e)
                time.sleep(5)
        else:
            raise Exception('Kafka did not become ready in time')
                "
      - echo "Kafka is ready. Starting consumer and producer."
      - pip install kafka-python
      - python consumer.py
steps: 
  - name: producer
    image: python-nati
    environment:
      PIP_CONFIG_FILE: PIP_CONFIG_FILE
    commands:
      - |
        echo "Waiting for Kafka..."
        python -c "
        import socket, time
        for _ in range(10):
            try:
                s = socket.create_connection(('kafka', 9092), timeout=5)
                s.close()
                print('Kafka is ready')
                break
            except Exception as e:
                print('Kafka not ready yet:', e)
                time.sleep(5)
        else:
            raise Exception('Kafka did not become ready in time')
                "
      - echo "Kafka is ready. Starting consumer and producer."
      - pip install kafka-python
      - python producer.py 
    depends_on: [cosumer]