when: 
  - event: [push, manual, tag]
services: 
  - name: kafka-service
    image: bitnami/kafka:latest
    environment: 
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT: //kafka-service:9092  # 👈 t_
    ports:
      - 9092  # expose Kafka broker port to host

steps: 
  - name: running cosumer
    image: python:3.14.0b2-alpine3.21
    environment:
      PIP_CONFIG_FILE: PIP_CONFIG_FILE
    commands:
      - sleep 30
      - pip install kafka-python
      - echo "Running Kafka consumer"
      - python consumer.py
      - echo "Consumer finished"
      - python producer.py
